### ISSUE TITLE
geohash int bitdepth broken

### ISSUE THREAD

**Issue by nenti** [sunng87/node-geohash#28]
```
location = "u281yyxg1"
location1 = 3669078753079491  // Bitdepth 52
location2 = 917269688269872  // Bitdepth 50
location3 = 895771179951  // Bitdepth 40
```

The integer locations are changing all digits when changing bitdepth on the same location. From my understanding the higher_order_digits need to be similar no matter what bitdepth is selected. There must be something wrong in the implementation.

**Comment by arjunmehta** [comment]
Hi @nenti,

This is not the way integer geohashes work. Integer geohashes are encoded with a certain **binary** bit depth, which are then converted to decimal. The more bits that are encoded, the more precise the area will be, the bigger the number will be etc.

For example a 6-bit geohash for an area may look like: `010101` = `21`
A 12-bit geohash for the same point will be hashed with more precision and even though it may have the same binary prefix will resolve into an entirely different number: `010101000011` = `1347`

Regular geohashes use base-32 characters instead of converting to base-10 integers, so it works very differently. You can knock off characters at the end and maintain a lower resolution geohash.

This is why you must always use the same bitdepth when encoding and decoding your integer geohashes.

I hope this helps.

**Comment by arjunmehta** [comment]
@nenti that's a good question. I see on the amazon site that it uses a very different integer representation than most other implementations I've seen for integer geohashing. I've also never seen spatial queries divide into 6 cells. Fascinating.

The main use cases of using the binary approach is to play nicely with other language implementations of integer geohashes, because they all do what you think is broken :):

Examples:
[C99](https://github.com/yinqiwen/geohash-int)
[Python-geohash](https://github.com/hkwi/python-geohash/wiki/GeohashReference)

Also many other databases are using the same method:
[Redis](https://github.com/antirez/redis/blob/unstable/src/geohash.c)
[Mongo-db](https://docs.mongodb.com/manual/core/geospatial-indexes/)

Another use case is to do what I think you want to do: [Find nearby points from each other](https://gis.stackexchange.com/questions/18330/using-geohash-for-proximity-searches/92331#92331).

I've written a [library here](https://github.com/arjunmehta/node-georedis) you may be interested in.

**Comment by nenti** [comment]
I thought that the integer representation would be a great way to be more precise in the steppings that you are doing on the rectangle selection. That's why I think amazon took the approach you are seeing there. Because in their dynamodb table you can use something called `begins_with` to query efficiently over your range keys.

I think it would be great if we could extend the `neighbors_int` and the `decode_bbox_int` function with the number of digits you wish to query for, to enable this use case for the 16 digit integer representation.

**Comment by arjunmehta** [comment]
@nenti I think you're conflating two notions. Bit depth and hash length.

On Amazon, they are consistently using 64-bit geohashes and using the first 6 numbers for indexing.

This is very different from modifying the bit depth and using that value for indexing.

Also, it's not clear what algorithm Amazon is using in their examples here. I've never seen the 6-cell approach to divide the earth (how does that work??).

Not only that, but the idea of using similar geohashes alone to find nearby points will not give accurate results. Two points right next to each other could have very different geohashes.
